version: 2.1

executors:
  docker:
    working_directory: ~/workspace
    docker:
      - image: docker:18.03-git

commands:
  docker_build:
    description: Push image to registory
    parameters:
      repository:
        type: string
    steps:
      - run:
          command: docker build -t << parameters.repository >> .

  docker_push:
    description: Push image to registory
    parameters:
      repository:
        type: string
    steps:
      - run:
          command: |
            export TAG=`date +%Y.%m.%d`
            docker tag << parameters.repository >> << parameters.repository >>:${TAG}
            docker push << parameters.repository >>:${TAG}
            docker tag << parameters.repository >> << parameters.repository >>:latest
            docker push << parameters.repository >>:latest

jobs:
  build_and_push_image_to_dockerhub:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker login
          command: docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
      - docker_build:
          repository: gunosy/neologd-for-mecab
      - docker_push:
          repository: gunosy/neologd-for-mecab

workflows:
  version: 2
  workflow:
    triggers:
      - schedule:
          cron: "0 0 * * 2,5"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_and_push_image_to_dockerhub:
          filters:
            branches:
              only:
                - master
