version: 2

jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: docker:18.03-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            docker build -t gunosy/neologd-for-mecab .
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              export TAG=`date +%Y.%m.%d`
              docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
              docker tag gunosy/neologd-for-mecab gunosy/neologd-for-mecab:"$TAG"
              docker push gunosy/neologd-for-mecab:"$TAG"
              docker tag gunosy/neologd-for-mecab gunosy/neologd-for-mecab:latest
              docker push gunosy/neologd-for-mecab:latest
            fi

workflows:
  version: 2
  workflow:
    triggers:
      - schedule:
          cron: "0 0 * * 2,5"
          filters:
            branches:
              only:
                - master
    jobs:
      - build

