version: 2.1

executors:
  docker:
    working_directory: ~/workspace
    docker:
      - image: docker:18.03-git

jobs:
  build_and_push_image_to_dockerhub:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
              export TAG=`date +%Y.%m.%d`
              docker build -t gunosy/neologd-for-mecab .
              docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
              docker tag gunosy/neologd-for-mecab gunosy/neologd-for-mecab:"$TAG"
              docker push gunosy/neologd-for-mecab:"$TAG"
              docker tag gunosy/neologd-for-mecab gunosy/neologd-for-mecab:latest
              docker push gunosy/neologd-for-mecab:latest

  build_and_push_image_to_quay:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
              export TAG=`date +%Y.%m.%d`
              docker build -t quay.io/gunosy/neologd-for-mecab .
              docker login quay.io -u "$QUAY_IO_USERNAME" -p "$QUAY_IO_PASSWORD"
              docker tag quay.io/gunosy/neologd-for-mecab quay.io/gunosy/neologd-for-mecab:"$TAG"
              docker push quay.io/gunosy/neologd-for-mecab:"$TAG"
              docker tag quay.io/gunosy/neologd-for-mecab quay.io/gunosy/neologd-for-mecab:latest
              docker push quay.io/gunosy/neologd-for-mecab:latest

workflows:
  version: 2
  workflow:
    triggers:
      - schedule:
          cron: "0 0 * * 2,5"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_and_push_image_to_dockerhub:
          filters:
            branches:
              only:
                - master
      - build_and_push_image_to_quay:
          filters:
            branches:
              only:
                - master
